$ErrorActionPreference = "Stop"
function Rgb([int]$r,[int]$g,[int]$b){ return $r + ($g*256) + ($b*65536) }
$ink=Rgb 45 50 59; $muted=Rgb 98 108 120; $light=Rgb 244 248 251; $line=Rgb 214 225 234; $blue=Rgb 15 94 142; $red=Rgb 190 57 42; $green=Rgb 69 176 94; $gold=Rgb 173 128 45; $white=Rgb 255 255 255; $orange=Rgb 238 124 48; $dark=Rgb 32 41 52
function AddText($slide,[string]$text,[double]$x,[double]$y,[double]$w,[double]$h,[double]$size=14,[bool]$bold=$false,[int]$color=0,[int]$align=1){
  $shape=$slide.Shapes.AddTextbox(1,$x,$y,$w,$h); $shape.TextFrame2.WordWrap=-1; $shape.TextFrame2.MarginLeft=2; $shape.TextFrame2.MarginRight=2; $shape.TextFrame2.MarginTop=1; $shape.TextFrame2.MarginBottom=1
  $r=$shape.TextFrame2.TextRange; $r.Text=$text; $r.Font.Name='Microsoft YaHei'; $r.Font.NameFarEast='Microsoft YaHei'; $r.Font.Size=$size; if($bold){$r.Font.Bold=-1}else{$r.Font.Bold=0}; $r.Font.Fill.ForeColor.RGB=$color; $r.ParagraphFormat.Alignment=$align; return $shape
}
function AddCard($slide,[double]$x,[double]$y,[double]$w,[double]$h,[int]$fill,[int]$border){ $s=$slide.Shapes.AddShape(5,$x,$y,$w,$h); $s.Fill.Visible=-1; $s.Fill.ForeColor.RGB=$fill; $s.Line.Visible=-1; $s.Line.ForeColor.RGB=$border; $s.Line.Weight=0.8; return $s }
function AddRect($slide,[double]$x,[double]$y,[double]$w,[double]$h,[int]$fill){ $s=$slide.Shapes.AddShape(1,$x,$y,$w,$h); $s.Fill.Visible=-1; $s.Fill.ForeColor.RGB=$fill; $s.Line.Visible=0; return $s }
function AddTitle($slide,[string]$title,[string]$sub=''){ AddText $slide $title 78 42 790 42 24 $true $ink 1 | Out-Null; if($sub){AddText $slide $sub 80 84 790 24 10.8 $false $muted 1|Out-Null} }
function AddFooter($slide,[int]$p){ AddText $slide '上海致宇信息技术有限公司' 760 515 145 12 6.8 $false $muted 3|Out-Null; AddText $slide '用技术简化知识工作' 78 515 110 12 6.8 $false $muted 1|Out-Null; AddText $slide ("{0:D2}" -f $p) 918 515 28 12 6.8 $false $muted 3|Out-Null }
function AddSection($slide,[string]$num,[string]$title,[string]$sub){ AddText $slide $num 420 160 70 30 22 $true $red 2|Out-Null; AddText $slide $title 180 235 600 50 30 $true $ink 2|Out-Null; AddText $slide $sub 225 292 510 24 12.5 $false $muted 2|Out-Null }
function ClearSlide($slide){ for($j=$slide.Shapes.Count;$j -ge 1;$j--){$slide.Shapes.Item($j).Delete()} }
function AddBullets($slide,[array]$items,[double]$x,[double]$y,[double]$w,[double]$h,[double]$size=13){ $txt=($items|ForEach-Object{"• $_"}) -join "`n"; AddText $slide $txt $x $y $w $h $size $false $ink 1|Out-Null }
function AddCode($slide,[string]$code,[double]$x,[double]$y,[double]$w,[double]$h){ AddCard $slide $x $y $w $h $light $line|Out-Null; $s=AddText $slide $code ($x+10) ($y+10) ($w-20) ($h-20) 8.4 $false $dark 1; $s.TextFrame2.TextRange.Font.Name='Consolas' }
function AddGrid($slide,[array]$items,[double]$x,[double]$y,[double]$w,[double]$h,[int]$cols=3){ $gapX=14; $gapY=14; $rows=[Math]::Ceiling($items.Count/$cols); $bw=($w-$gapX*($cols-1))/$cols; $bh=($h-$gapY*($rows-1))/$rows; for($i=0;$i -lt $items.Count;$i++){ $row=[Math]::Floor($i/$cols); $col=$i%$cols; $bx=$x+$col*($bw+$gapX); $by=$y+$row*($bh+$gapY); AddCard $slide $bx $by $bw $bh $light $line|Out-Null; AddText $slide ([string]($i+1)) ($bx+8) ($by+10) 16 12 7.8 $true $red 1|Out-Null; AddText $slide $items[$i][0] ($bx+30) ($by+9) ($bw-40) 18 10.8 $true $ink 1|Out-Null; AddText $slide $items[$i][1] ($bx+12) ($by+36) ($bw-24) ($bh-42) 8.4 $false $muted 2|Out-Null }}
function AddTimeline($slide){
  $years=@('1980s-2000s','2014','2015','2016','2019','2022+')
  $titles=@('传统登记证照','信用公示入口','三证合一','五证合一','新版执照','规范化/电子化')
  $subs=@('注册号时代，地区和版式差异大','企业信用信息开始成为监管入口','统一社会信用代码成为企业身份主键','多证整合减少材料重复提交','横版样式、二维码、公示入口更稳定','字段、版式、电子证照继续统一')
  $colors=@($blue,$green,$blue,$orange,$red,$dark)
  $x=105; $y=240; $seg=120
  AddRect $slide $x ($y+23) ($seg*6) 18 (Rgb 218 224 230)|Out-Null
  for($i=0;$i -lt 6;$i++){ $sx=$x+$i*$seg; AddRect $slide $sx ($y+18) ($seg-4) 28 $colors[$i]|Out-Null; AddText $slide $years[$i] ($sx+6) ($y+24) ($seg-16) 12 8 $true $white 2|Out-Null; if($i%2 -eq 0){$ty=$y-86;$lineY=$y+18}else{$ty=$y+66;$lineY=$y+46}; $ln=$slide.Shapes.AddLine(($sx+$seg/2),$lineY,($sx+$seg/2),($ty+42)); $ln.Line.ForeColor.RGB=$muted; $ln.Line.Weight=0.8; AddText $slide $titles[$i] ($sx-20) $ty 150 18 10.5 $true $ink 2|Out-Null; AddText $slide $subs[$i] ($sx-25) ($ty+22) 160 38 8.2 $false $muted 2|Out-Null }
}
function AddPie($slide){
  $vals=@(35,25,20,20); $labels=@('字段错配','语义错字','长文本截断','版面噪声'); $colors=@($red,$gold,$blue,$green); $start=0; $cx=240; $cy=255; $r=120
  for($i=0;$i -lt $vals.Count;$i++){ $end=$start+360*$vals[$i]/100; $pie=$slide.Shapes.AddShape(142, $cx-$r, $cy-$r, $r*2, $r*2); $pie.Fill.ForeColor.RGB=$colors[$i]; $pie.Line.ForeColor.RGB=$white; $pie.Adjustments.Item(1)=$start; $pie.Adjustments.Item(2)=$end; $start=$end }
  for($i=0;$i -lt $labels.Count;$i++){ AddRect $slide 440 (170+$i*45) 14 14 $colors[$i]|Out-Null; AddText $slide ($labels[$i]+'  '+$vals[$i]+'%') 465 (166+$i*45) 160 18 11.2 $true $ink 1|Out-Null }
}

$template=(Get-ChildItem 'D:\OCR_Research\company_share' -Filter '*.pptx'|Where-Object{ -not $_.Name.StartsWith('~$') -and $_.Name -like '*AgenticADE*20260604.pptx'}|Select-Object -First 1).FullName
$out='D:\OCR_Research\company_share\营业执照AgentOCR技术分享_套模板_v2.pptx'
$preview='D:\OCR_Research\company_share\ppt_preview_template_v2'
Copy-Item $template $out -Force
$pp=New-Object -ComObject PowerPoint.Application
$pres=$pp.Presentations.Open($out,$false,$false,$false)
while($pres.Slides.Count -gt 24){$pres.Slides.Item($pres.Slides.Count).Delete()}
while($pres.Slides.Count -lt 24){$pres.Slides.Add($pres.Slides.Count+1,12)|Out-Null}
for($i=1;$i -le $pres.Slides.Count;$i++){ ClearSlide $pres.Slides.Item($i) }

$s=$pres.Slides.Item(1); AddText $s '营业执照 Agent OCR 实践' 165 140 640 48 32 $true $ink 2|Out-Null; AddText $s '从版式演变、工具调用到可信字段 JSON' 190 202 590 32 20 $true $red 2|Out-Null; AddText $s 'PaddleOCR-VL-1.6 / LangChain / 大模型语义后处理 / Skill 沉淀' 220 255 530 22 12.5 $false $muted 2|Out-Null; AddText $s "分享人：李岗威`n时间：2026-06-10" 680 405 160 44 11.5 $false $ink 1|Out-Null; AddFooter $s 1
$s=$pres.Slides.Item(2); AddText $s '目录' 80 70 120 34 28 $true $ink 1|Out-Null; AddText $s 'CONTENTS' 82 105 110 16 9.5 $false $gold 1|Out-Null; $contents=@(@('01','营业执照常识：版式演变与字段变化','为什么它适合作为 Agent OCR 的业务对象'),@('02','OCR 难点：从看见文字到可信字段','错误样本、错误类型和修复边界'),@('03','理论主线：工具调用与 LangChain','用简单语言讲清楚 Agent 怎么用工具'),@('04','Demo 实践：图片、代码、输出结果','展示真实代码，而不只是流程图'),@('05','沉淀 Skill：可复用业务与环境经验','把踩坑和流程沉淀成下一次可复用资产')); for($i=0;$i -lt $contents.Count;$i++){ $y=145+$i*66; AddText $s $contents[$i][0] 95 $y 36 24 16 $true $red 1|Out-Null; AddText $s $contents[$i][1] 145 ($y-2) 560 24 15.5 $true $ink 1|Out-Null; AddText $s $contents[$i][2] 146 ($y+25) 560 18 9.8 $false $muted 1|Out-Null}; AddFooter $s 2
$s=$pres.Slides.Item(3); AddSection $s '01' '营业执照常识' '先理解证照制度和字段变化，再谈识别难点'; AddFooter $s 3
$s=$pres.Slides.Item(4); AddTitle $s '营业执照版式演变：从登记凭证到企业身份入口' '参考 wiki「营业执照版式演变与字段变化」主题，先建立业务常识，再进入技术实现。'; AddTimeline $s; AddFooter $s 4
$s=$pres.Slides.Item(5); AddTitle $s '真实版式样本：同样是营业执照，版式和字段并不完全一致' '这一页用于建立直觉：模型看到的不是一种固定模板，而是一组有历史演变的证照版式。'; $imgs=@('D:\OCR_Research\agent\data\188.jpg','D:\OCR_Research\agent\data\2_2.jpg','D:\OCR_Research\agent\data\Snipaste_2026-06-04_15-12-26.jpg'); $labs=@('横版副本样本','新版企业样本','分享对象样本'); for($i=0;$i -lt 3;$i++){ $x=95+$i*255; if(Test-Path $imgs[$i]){$s.Shapes.AddPicture($imgs[$i],$false,$true,$x,155,215,130)|Out-Null}; AddText $s $labs[$i] $x 298 215 16 10.5 $true $blue 2|Out-Null; AddText $s '可替换为你后续收集的真实版式截图' $x 320 215 18 8.5 $false $muted 2|Out-Null }; AddFooter $s 5
$s=$pres.Slides.Item(6); AddTitle $s '版式变化会带来字段变化：同一位置、同一人名，不一定是同一法律含义' '这里不要只讲 key 名，要讲字段背后的主体类型和法律语义。'; $heads=@('主体类型','人名字段 key','法律意义','识别风险'); $xs=@(95,245,430,630); $ws=@(150,185,200,210); for($c=0;$c -lt 4;$c++){AddCard $s $xs[$c] 145 $ws[$c] 30 $blue $blue|Out-Null; AddText $s $heads[$c] ($xs[$c]+4) 153 ($ws[$c]-8) 12 8.8 $true $white 2|Out-Null}; $rows=@(@('公司','法定代表人','代表公司行使职权的人','误识别为经营者会改变主体责任'),@('合伙企业','执行事务合伙人','受托执行合伙事务的人','同为人名，但不是法定代表人'),@('个体工商户','经营者','直接经营并承担责任的人','不能映射为法人代表'),@('分支机构','负责人','负责分支机构经营的人','不对应注册资本逻辑')); for($r=0;$r -lt $rows.Count;$r++){for($c=0;$c -lt 4;$c++){ $y=175+$r*46; AddCard $s $xs[$c] $y $ws[$c] 46 $light $line|Out-Null; AddText $s $rows[$r][$c] ($xs[$c]+5) ($y+15) ($ws[$c]-10) 12 8.4 $false $ink 2|Out-Null }}; AddText $s '讲法：OCR 看到的是「人名」，业务系统要判断它到底是法定代表人、经营者、负责人，还是执行事务合伙人。' 110 405 720 30 14.2 $true $red 2|Out-Null; AddFooter $s 6
$s=$pres.Slides.Item(7); AddSection $s '02' 'OCR 难点' '营业执照真正难的，是把识别结果变成可信字段'; AddFooter $s 7
$s=$pres.Slides.Item(8); AddTitle $s '错误类型可以用「分布 + 样本」来讲，会比纯文字更直观' '左侧是建议的错误类型分布，右侧留给后续替换真实错误截图。'; AddPie $s; $samples=@(@('字段错配','把旧执照/说明文字中的内容当成目标字段'),@('语义错字','临颍/临颖、造价/浩价、记账/记帐'),@('长文本截断','经营范围换行、括号、许可项目被截断')); for($i=0;$i -lt 3;$i++){ $y=160+$i*90; AddCard $s 650 $y 220 62 $light $line|Out-Null; AddText $s $samples[$i][0] 668 ($y+12) 80 14 10.5 $true $red 1|Out-Null; AddText $s $samples[$i][1] 668 ($y+34) 180 18 8.8 $false $ink 1|Out-Null}; AddText $s '这些比例先作为讲解框架，等你补充真实错误样本后，可以替换为真实统计。' 105 430 760 22 12.5 $false $muted 2|Out-Null; AddFooter $s 8
$s=$pres.Slides.Item(9); AddTitle $s '为什么需要 Agent：OCR 只回答「看到了什么」，Agent 要回答「可信不可信」' '如果只做 OCR，输出文本就结束了；Agent 会把文本变成可校验、可修复、可解释的业务结果。'; AddGrid $s @(@('看见','OCR/VL 模型读取图片和版面'),@('抽取','把全文映射到营业执照字段'),@('校验','信用代码、日期、金额做确定性检查'),@('修复','规则修复 + LLM 语义修复'),@('解释','保留 tool_trace 和 repair_actions'),@('输出','可信 JSON 和运行摘要')) 95 155 760 210 3; AddFooter $s 9
$s=$pres.Slides.Item(10); AddSection $s '03' '工具调用与 LangChain' '用简单语言讲清楚 Agent 怎么用工具'; AddFooter $s 10
$s=$pres.Slides.Item(11); AddTitle $s '什么是智能体的工具调用？可以理解为「模型会请专业工具帮忙」' '模型本身负责判断下一步，工具负责做确定性的外部动作。'; AddGrid $s @(@('普通问答','模型直接生成答案，过程不可控'),@('工具调用','模型选择一个函数，并传入参数'),@('工具执行','函数访问 OCR、数据库、规则校验器或 API'),@('观察结果','模型读取工具返回值，决定继续还是结束'),@('可追踪','每一步都能记录名称、输入、输出、耗时'),@('可复用','换业务时保留框架，替换工具')) 95 150 760 220 3; AddText $s '一句话：Agent 不是「更聪明的 OCR」，而是「会组织 OCR、规则和大模型一起完成任务的流程控制器」。' 115 420 720 26 16 $true $red 2|Out-Null; AddFooter $s 11
$s=$pres.Slides.Item(12); AddTitle $s '什么是 LangChain？它像一套「把工具接到模型上的插排」' '不用把全部流程写死在一个函数里，而是把每个动作包装成工具，再由 Agent 编排。'; AddCard $s 100 155 215 210 $light $line|Out-Null; AddText $s '没有 LangChain' 125 175 160 18 13 $true $red 2|Out-Null; AddBullets $s @('脚本里手写 if/else','步骤之间耦合重','换模型或工具麻烦','不容易记录工具轨迹') 125 215 160 110 11.2; AddCard $s 385 155 215 210 $light $line|Out-Null; AddText $s '使用 LangChain' 410 175 160 18 13 $true $blue 2|Out-Null; AddBullets $s @('StructuredTool 定义工具','模型/流程调用工具','输入输出结构化','更容易扩展和演示') 410 215 160 110 11.2; AddCard $s 660 155 215 210 $light $line|Out-Null; AddText $s '本 demo 的落地' 685 175 160 18 13 $true $green 2|Out-Null; AddBullets $s @('抽取字段工具','校验字段工具','规则修复工具','LLM 语义修复工具') 685 215 160 110 11.2; AddFooter $s 12
$s=$pres.Slides.Item(13); AddTitle $s '本项目里，LangChain 工具就是这四个函数' '这一页开始把抽象概念落到真实代码。'; AddCode $s "tools = [`n  StructuredTool.from_function(`n    func=extract_business_license_fields_tool,`n    name='extract_business_license_fields',`n    description='从 OCR 全文中抽取中文字段'`n  ),`n  StructuredTool.from_function(`n    func=validate_business_license_fields_tool,`n    name='validate_business_license_fields',`n    description='校验信用代码、日期、金额'`n  ),`n  StructuredTool.from_function(`n    func=repair_business_license_fields_tool,`n    name='repair_business_license_fields'`n  ),`n  StructuredTool.from_function(`n    func=llm_semantic_repair_business_license_fields_tool,`n    name='llm_semantic_repair_business_license_fields'`n  ),`n]" 95 140 470 285; AddBullets $s @('每个工具都有函数名、工具名、说明文本','说明文本帮助模型/流程知道什么时候调用它','工具返回结构化 dict，便于继续校验和修复') 600 180 260 150 12.5; AddFooter $s 13
$s=$pres.Slides.Item(14); AddSection $s '04' 'Demo 实践' '从图片、代码到可信 JSON'; AddFooter $s 14
$s=$pres.Slides.Item(15); AddTitle $s 'Demo 流程：图片进入，可信 JSON 出来' '当前默认参数已经指向样例营业执照图片，运行 app.py 即可走完整链路。'; if(Test-Path 'D:\OCR_Research\agent\data\188.jpg'){$s.Shapes.AddPicture('D:\OCR_Research\agent\data\188.jpg',$false,$true,80,135,340,240)|Out-Null}; AddGrid $s @(@('图片输入','data/188.jpg'),@('OCR','PaddleOCR-VL-1.6'),@('字段抽取','中文字段'),@('校验','格式和规则'),@('LLM 修复','语义后处理'),@('结果保存','outputs/*.json')) 460 148 360 166 3; AddText $s '演示命令' 470 385 80 16 11.5 $true $blue 1|Out-Null; AddCard $s 460 412 360 46 $light $line|Out-Null; AddText $s 'python app.py' 485 428 315 16 14 $true $ink 1|Out-Null; AddFooter $s 15
$s=$pres.Slides.Item(16); AddTitle $s '代码 1：默认参数让现场演示少输入、少出错' '这解释了为什么你现在直接 python app.py 就会走默认图片链路。'; AddCode $s "parser.add_argument('--mode', default='image')`nparser.add_argument('--image-path', default=r'D:\OCR_Research\agent\data\188.jpg')`nparser.add_argument('--ocr-out', default=r'D:\OCR_Research\agent\output')`n`noutput_path = choose_output_path(args)`nuse_llm_postprocess = choose_llm_postprocess(args)`n`nif args.mode == 'image':`n    ocr_meta = run_paddleocr_vl(args.image_path, args.ocr_out)`n    ocr_text = ocr_meta['text']" 95 140 520 250; AddBullets $s @('默认 image 模式，避免现场忘记传参数','默认图片路径固定，确保 demo 可重复','默认输出路径固定，方便告诉大家结果保存在哪里','检测到 API key 时自动启用大模型后处理') 650 165 230 170 12; AddFooter $s 16
$s=$pres.Slides.Item(17); AddTitle $s '代码 2：Agent 编排工具链，不是一个黑盒函数' 'tool_trace 会记录每一步工具、目的、观察结果和耗时。'; AddCode $s "extracted = tools['extract_business_license_fields'].invoke({'ocr_text': ocr_text})`nfirst_pass = tools['validate_business_license_fields'].invoke({'fields': extracted})`nrepaired = tools['repair_business_license_fields'].invoke({`n    'fields': extracted,`n    'validation': first_pass,`n})`nif self.use_llm_postprocess:`n    llm_postprocess = tools['llm_semantic_repair_business_license_fields'].invoke({`n        'ocr_text': ocr_text,`n        'fields': repaired['fields'],`n    })`nfinal_validation = tools['validate_business_license_fields'].invoke({'fields': final_fields})" 95 135 560 285; AddBullets $s @('抽取：从全文找到字段','校验：确定性规则先挡住明显错误','规则修复：处理 O/0、I/1 等混淆','LLM 修复：处理语义和字段边界','再次校验：修复后仍要验证') 685 155 190 190 11.5; AddFooter $s 17
$s=$pres.Slides.Item(18); AddTitle $s '代码 3：大模型后处理不是乱改，而是被严格约束' 'prompt 明确要求只修复有依据的 OCR 错字，并且只输出 JSON。'; AddCode $s "严格规则：`n1. 只能修复 OCR 明显错字、字段粘连、标签混入、常见字符混淆。`n2. 不要编造 OCR 全文中没有依据的信息。`n3. 统一社会信用代码、日期、金额如果没有把握，不要修改。`n4. 经营范围可以根据营业执照常见语义修复明显错字，但必须保守。`n5. 只输出 JSON，不要输出解释性文字。" 95 145 520 220; AddBullets $s @('LLM 负责语义候选，不负责最终拍板','规则和权威库仍然是兜底','保留 actions，知道它改了什么、为什么改','低置信度修复应进入人工复核') 650 165 230 155 12; AddFooter $s 18
$s=$pres.Slides.Item(19); AddTitle $s '运行结果：这次图片链路确实经过了 OCR 和大模型' '摘要中能看到 OCR 模型、LLM 模型、耗时和结果保存路径。'; $metrics=@(@('OCR 模型','PaddleOCR-VL-1.6',$blue),@('大模型','claude-sonnet-4-6',$red),@('大模型耗时','14.256 秒',$green),@('自动修复字段','7 个',$gold)); for($i=0;$i -lt $metrics.Count;$i++){ $x=95+$i*185; AddCard $s $x 150 160 65 $light $line|Out-Null; AddText $s $metrics[$i][1] ($x+10) 163 140 18 12.5 $true $metrics[$i][2] 2|Out-Null; AddText $s $metrics[$i][0] ($x+10) 192 140 12 8.5 $false $muted 2|Out-Null}; AddCode $s "========== 运行摘要 ==========`n输入类型：图片`n输入路径：D:\OCR_Research\agent\data\188.jpg`nOCR 模型：PaddleOCR-VL-1.6`n调用模型：claude-sonnet-4-6`n大模型耗时：14.256 秒`n结果已保存：D:\OCR_Research\agent\outputs\license_image_agent_result.json" 135 260 700 150; AddFooter $s 19
$s=$pres.Slides.Item(20); AddTitle $s '修复结果示例：从 OCR 字段到可信字段' '讲这页时重点强调：修复动作保存在 repair_actions，不是静默覆盖。'; $heads=@('字段','修复前','修复后'); $xs=@(95,260,530); $ws=@(165,270,310); for($c=0;$c -lt 3;$c++){AddCard $s $xs[$c] 145 $ws[$c] 30 $blue $blue|Out-Null; AddText $s $heads[$c] ($xs[$c]+4) 153 ($ws[$c]-8) 12 8.8 $true $white 2|Out-Null}; $rows=@(@('统一社会信用代码','92440300MA5FPG0XXH','91110108306767909G'),@('类型','个体工商户','有限责任公司（自然人独资）'),@('法定代表人','薛丁川','刘福喜'),@('住所','深圳市宝安区...佛商大厦027','北京市海淀区中关村大街...405室')); for($r=0;$r -lt $rows.Count;$r++){for($c=0;$c -lt 3;$c++){ $y=175+$r*48; AddCard $s $xs[$c] $y $ws[$c] 48 $light $line|Out-Null; AddText $s $rows[$r][$c] ($xs[$c]+5) ($y+16) ($ws[$c]-10) 12 8.3 $false $ink 2|Out-Null }}; AddText $s '注意：这类修复后续最好接入行政区划库、企业信用公示数据做二次确认。' 120 420 710 22 13.5 $true $red 2|Out-Null; AddFooter $s 20
$s=$pres.Slides.Item(21); AddSection $s '05' '沉淀 Skill' '把一次 demo 变成可复用的方法'; AddFooter $s 21
$s=$pres.Slides.Item(22); AddTitle $s '业务 Skill：沉淀「营业执照怎么识别」' '不是一句空泛的总结，而是把字段、规则、修复策略写成下一次可用的工作手册。'; AddGrid $s @(@('字段清单','统一社会信用代码、名称、类型、负责人、资本、地址、经营范围等'),@('字段别名','法定代表人/经营者/负责人/执行事务合伙人'),@('校验规则','信用代码校验位、日期格式、金额格式'),@('修复策略','O/0、I/1、标签混入、字段粘连'),@('输出契约','final_fields、repair_actions、summary'),@('演示讲法','OCR 负责看见，Agent 负责可信')) 95 150 760 230 3; AddFooter $s 22
$s=$pres.Slides.Item(23); AddTitle $s '环境 Skill：沉淀「本地怎么跑起来」' '这部分对以后最有用：代理、证书、模型缓存、CPU 慢的问题，下次不用重新摸索。'; AddBullets $s @('conda 环境：company_tool','模型：PaddleOCR-VL-1.6，本地 CPU 可跑但耗时较长','代理：模型下载失败时配置 HTTP_PROXY / HTTPS_PROXY','证书：SSL_CERT_FILE 指向 certifi cacert.pem，避免 FileNotFoundError','API key：setx 后当前终端不生效，代码读取 Windows 用户环境变量兜底','默认参数：python app.py 即可演示，不要求现场输入长命令') 120 150 720 230 15; AddFooter $s 23
$s=$pres.Slides.Item(24); AddTitle $s '总结：这次分享的重点不是 OCR，而是让 OCR 结果变得可信' '从业务常识、工具调用、代码实战到 Skill 沉淀，形成一个可复用的 Agent OCR 范式。'; AddGrid $s @(@('业务上','理解营业执照版式和字段法律语义'),@('技术上','PaddleOCR-VL + LangChain 工具链 + LLM 后处理'),@('工程上','默认参数、运行摘要、输出路径、可追踪 repair_actions'),@('复用上','业务 Skill + 环境 Skill，减少下一次踩坑')) 120 160 720 170 2; AddText $s 'Q&A' 420 410 120 30 24 $true $ink 2|Out-Null; AddFooter $s 24

$pres.Save()
if(Test-Path $preview){Remove-Item $preview -Recurse -Force}
New-Item -ItemType Directory -Force -Path $preview|Out-Null
$pres.Export($preview,'PNG',1280,720)
$cnt=$pres.Slides.Count
$pres.Close(); $pp.Quit(); [System.Runtime.InteropServices.Marshal]::ReleaseComObject($pres)|Out-Null; [System.Runtime.InteropServices.Marshal]::ReleaseComObject($pp)|Out-Null
Write-Output "output=$out"; Write-Output "slides=$cnt"; Write-Output "preview=$preview"
